---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tzcronjobs.cronjobber.hidde.co
spec:
    group: cronjobber.hidde.co
    version: v1alpha1
    names:
      plural: tzcronjobs
      singular: tzcronjob
      kind: TZCronJob
      listKind: TZCronJobList
      shortNames:
      - tzc
    scope: Namespaced
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Schedule
      type: string
      description: The schedule defining the interval a TZCronJob is run
      JSONPath: .spec.schedule
    - name: Time zone
      type: string
      description: The time zone the interval of a TZCronJob is calculated in
      JSONPath: .spec.timezone
    - name: Last schedule
      type: date
      description: The last time a Job was scheduled by a TZCronJob
      JSONPath: .status.lastScheduleTime
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp