---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjobber
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cronjobber
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: cronjobber
    spec:
      serviceAccountName: cronjobber
      securityContext:
        runAsUser: 65534 #nobody
        fsGroup: 65534 #nobody
      volumes:
      - name: timezonedb
        hostPath:
          path: /usr/share/zoneinfo
          type: Directory
      containers:
      - name: cronjobber
        image: quay.io/hiddeco/cronjobber:0.1.1
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        args:
        - --log-level=info
        volumeMounts:
        - name: timezonedb
          mountPath: /usr/share/zoneinfo
          readOnly: true
