---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjobber
  labels:
    name: cronjobber
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cronjobber
  labels:
    name: cronjobber
rules:
  - apiGroups: ['cronjobber.hidde.co']
    resources: ['*']
    verbs: ['*']
  - apiGroups: ['batch']
    resources: ['jobs']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['create', 'patch', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cronjobber
  labels:
    name: cronjobber
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjobber
subjects:
  - kind: ServiceAccount
    name: cronjobber
    namespace: default
